// <auto-generated />
using System;
using ExamApp.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamApp.Migrations
{
    [DbContext(typeof(ExamAppDbContext))]
    [Migration("20240706140800_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamApp.Entities.Ders", b =>
                {
                    b.Property<string>("Kod")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("Ad")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("MuellimAd")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MuellimSoyad")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("Sinif")
                        .HasColumnType("numeric(2, 0)");

                    b.HasKey("Kod");

                    b.ToTable("Ders");

                    b.HasData(
                        new
                        {
                            Kod = "RIY",
                            Ad = "Riyaziyyat",
                            MuellimAd = "Riyaziyyat Muellimi",
                            MuellimSoyad = "Riyaziyyat Muellimi"
                        },
                        new
                        {
                            Kod = "FIZ",
                            Ad = "Fizika",
                            MuellimAd = "Fizika Muellimi",
                            MuellimSoyad = "Fizika Muellimi"
                        });
                });

            modelBuilder.Entity("ExamApp.Entities.Imtahan", b =>
                {
                    b.Property<decimal>("Nomre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(14, 0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Nomre"));

                    b.Property<string>("DersKod")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<decimal?>("Qiymet")
                        .HasColumnType("numeric(1, 0)");

                    b.Property<decimal?>("ShagirdNomre")
                        .HasColumnType("numeric(5, 0)");

                    b.Property<DateTime?>("Tarix")
                        .HasColumnType("date");

                    b.HasKey("Nomre");

                    b.HasIndex("DersKod");

                    b.HasIndex("ShagirdNomre");

                    b.ToTable("Imtahan");

                    b.HasData(
                        new
                        {
                            Nomre = 123m,
                            DersKod = "RIY",
                            Qiymet = 9m,
                            ShagirdNomre = 12345m,
                            Tarix = new DateTime(2024, 7, 6, 18, 7, 59, 630, DateTimeKind.Local).AddTicks(5753)
                        },
                        new
                        {
                            Nomre = 124m,
                            DersKod = "FIZ",
                            Qiymet = 9m,
                            ShagirdNomre = 54321m,
                            Tarix = new DateTime(2024, 7, 6, 18, 7, 59, 630, DateTimeKind.Local).AddTicks(5769)
                        });
                });

            modelBuilder.Entity("ExamApp.Entities.Shagird", b =>
                {
                    b.Property<decimal>("Nomre")
                        .HasColumnType("numeric(5, 0)");

                    b.Property<string>("Ad")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal?>("Sinif")
                        .HasColumnType("numeric(2, 0)");

                    b.Property<string>("Soyad")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Nomre");

                    b.ToTable("Shagird");

                    b.HasData(
                        new
                        {
                            Nomre = 12345m,
                            Ad = "Shagird1",
                            Sinif = 9m,
                            Soyad = "Shagird1"
                        },
                        new
                        {
                            Nomre = 54321m,
                            Ad = "Shagird1",
                            Sinif = 9m,
                            Soyad = "Shagird1"
                        });
                });

            modelBuilder.Entity("ExamApp.Entities.Imtahan", b =>
                {
                    b.HasOne("ExamApp.Entities.Ders", "Ders")
                        .WithMany("Imtahanlar")
                        .HasForeignKey("DersKod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamApp.Entities.Shagird", "Shagird")
                        .WithMany("Imtahanlar")
                        .HasForeignKey("ShagirdNomre");

                    b.Navigation("Ders");

                    b.Navigation("Shagird");
                });

            modelBuilder.Entity("ExamApp.Entities.Ders", b =>
                {
                    b.Navigation("Imtahanlar");
                });

            modelBuilder.Entity("ExamApp.Entities.Shagird", b =>
                {
                    b.Navigation("Imtahanlar");
                });
#pragma warning restore 612, 618
        }
    }
}
